### PR TITLE
Fix the last tab indentation

### PR DESCRIPTION
**Pull request by char101**
Hi,

So it seems that the problem is with the `SessionStore`. By setting the 2nd parameter of `_beginRemoveTabs`, the tab is not stored in the `SessionStore` closed tab list. But I suspect somewhere Tree Style Tabs uses this information.

So as as solution which seems to work with my limited testing, I use the normal `removeTab` method and remove the tab from the recently closed tab list by using the (_undocumented_) `forgetClosedTab` method.

### CODE REVIEW

**Comment by NiklasGollenstede** [comment]
Unfortunately, there is a limit to the number of tabs you can restore, which means that `gSessionStore.getClosedTabCount(gWindow)` will never return a value greater than 10.
Is there  a reason why you added the `lastClosedTabCount` test, or was that just a precaution?

**Comment by NiklasGollenstede** [comment]
I have added a commit ( ab3387e) that removes the check, and also uploaded it as a beta version to <a href="https://addons.mozilla.org/addon/unloadtabs/versions/">AMO</a>

**Comment by char101** [comment]
Not all closed tabs are added to the list: [`_shouldSaveTabState`](https://dxr.mozilla.org/mozilla-central/source/browser/components/sessionstore/SessionStore.jsm#3892).

**Comment by NiklasGollenstede** [comment]
Ah, Ok.

Something like this should work then,  shouldn't it?
```js
const needToForget = gSessionStore._shouldSaveTabState(tab);
gBrowser.removeTab(tab);
needToForget && gSessionStore.forgetClosedTab(gBrowser.ownerGlobal, 0);
```

**Comment by char101** [comment]
Unfortunately the parameter is not the `tab` but an object constructed [here](https://dxr.mozilla.org/mozilla-central/source/browser/components/sessionstore/SessionStore.jsm#1771), which is an implementation detail and not part of the API. That's why I didn't use it.

Ideally I think you could add a timestamp to the session data and then _peek_ the closed tab list and compare the timestamp to verify that it is the correct tab.

**Comment by NiklasGollenstede** [comment]
Yeah, I missed that.
But the timestamp thing is pretty ugly ... . I'll think about that, maybe I can come up with something better.
Maybe there is a way to temporaryly increase the value that `browser.sessionstore.max_tabs_undo ` sets.

**Comment by char101** [comment]
Alternatively you could save/restore the whole closed tabs list

```javascript
let SessionStoreNS = Components.utils.import('resource:///modules/sessionstore/SessionStore.jsm', {});

// save closed tabs list
let closedTabs = JSON.parse(gSessionStore.getClosedTabData(gBrowser.ownerGlobal);

// restore closed tabs list
SessionStoreNS.SessionStoreInternal._windows[gBrowser.ownerGlobal.__SSi]._closedTabs = closedTabs;
```

**Comment by char101** [comment]
By the way, the comment on `forgetClosedTab` says

```javascript
// default to the most-recently closed tab
aIndex = aIndex || 0;
```

but here

```javascript
saveClosedTabData(closedTabs, tabData) {
    // Find the index of the first tab in the list
    // of closed tabs that was closed before our tab.
    let index = closedTabs.findIndex(tab => {
      return tab.closedAt < tabData.closedAt;
    });

    // If we found no tab closed before our
    // tab then just append it to the list.
    if (index == -1) {
      index = closedTabs.length;
    }
```

the default position is at the end.

So I think the correct index is the last index not 0:

```javascript
gSessionStore.forgetClosedTab(gBrowser.ownerGlobal, gSessionStore.getClosedTabCount() - 1);
```

**Comment by char101** [comment]
I agree that temporarily modifying the `max_tabs_undo` is better since it does not access the internal variables of `SessionStoreInternal`.

```javascript
let prefBranch = Services.prefs.getBranch("browser.");
let maxTabsUndo = prefBranch.getIntPref('sessionstore.max_tabs_undo');
prefBranch.setIntPref('sessionstore.max_tabs_undo', maxTabsUndo + 1);
gBrowser.removeTab(tab);
// still need to check here that the tab is actually stored in the closed tabs list
prefBranch.setIntPref('sessionstore.max_tabs_undo', maxTabsUndo); // will remove the last entry
```

**Comment by NiklasGollenstede** [comment]
That looks good, I'll implement something along those lines tomorrow.
But now it's 4am where I live, so I _really_ need to go to bed.
And thanks! (you were pretty quick funding that stuff)

**Comment by NiklasGollenstede** [comment]
Ok. Same thing again:
I have added a commit (`68b668b`) that adds the `maxTabsUndo` and `lastClosedTabCount` logic, and also uploaded it as a beta version to <a href="https://addons.mozilla.org/addon/unloadtabs/versions/">AMO</a>.
To me it seems to be working, so it would be nice if you could test it with Tree Style Tabs in a real-world browser for a while.

**Pull request merged**
