### PR TITLE
Add unload subtree menu item

### PR DESCRIPTION
**Pull request by char101**
Adds an unload tree menu item for tree style tab. 

menu

### CODE REVIEW

**Comment by NiklasGollenstede** [comment]
Looks very good again.

With now three menu items, it was time for some restructuring in that section though: 7685c616ca6ef487549a6849784a727308eea579

Also, the `unloadTab` function is still buggy:
Before:
screenshot - sep 27 2016 12 11 pm
After unload (of the entire tree):
screenshot - sep 27 2016 12 08 pm
The very last tab of the tree tends to end up as a top level tab if it was previously nested. If there is another tab beneath it, this doesn't happen.

Also I saw it swap subtrees.

Would you care to debug this?

**Comment by char101** [comment]
Hi,

Unfortunately I cannot reproduce this behavior.

Before
a

Click unload other tabs
b

After
c

**Comment by NiklasGollenstede** [comment]
Damn, I uploaded the images in the wrong order -.-

Before needs to be after, and after before:
> The very last tab of the tree tends to end up as a top level tab <b>if it was previously nested</b>. 

In your setup it won't happen. Sorry for the confusion.

**Comment by char101** [comment]
Thanks for the clarification. I can reproduce the bug sucessfully :ok_hand:.

**Comment by NiklasGollenstede** [comment]
Well, that's just awesome, or not ...

Anyway, are you looking into this?

**Pull request merged**
